### ISSUE TITLE
help.wiki not respected

### ISSUE THREAD

**Issue by wojsmol** [joomla/help.joomla.org#1]
Hello
I work with the Polish TT coordinator Stefan anf @yild on launching Polish Help Server. A test version of the proxy based on this application communicates already with the wiki. The problem on this momennt is the fact that the setting `help.wiki` is not respected. Could I ask for a sample config.json with this setting?

Related https://github.com/joomla/joomla-cms/issues/11434
Regards

**Comment by mbabker** [comment]
[This gist](https://gist.github.com/mbabker/0c5eacb3ba0d159e52dd55732c1cbaf5) has an example config with all of the possible config values that are supported right now.

**Comment by yild** [comment]
Regarding first post.

Test virtual machine with installed help system proxy with config file config.json:
<quote>
{
	"system": {
		"error_reporting": 0
	},
	"log": {
		"level": "all"
	},
	"cache": {
		"enabled": false,
		"lifetime": 900,
		"adapter": "file"
	},
	"help": {
	    "wiki": "http://wiki.joomla.pl",
	    "wiki_max_redirects": 5
	}
}
</quote>
http://wiki.joomla.pl - thats polish help site,

my helpsites.xml file is like this (nice encoding btw):
<quote>
<?xml version="1.0" encoding="iso-8859-1"?>
<joshelp>
	<sites>
		<site tag="en-GB" url="https://help.joomla.org/proxy/index.php?option=com_help&amp;keyref=Help{major}{minor}:{keyref}">English (GB) - Joomla help wiki</site>
		<site tag="fr-FR" url="http://help.joomla.fr/3/index.php?option=com_help&amp;keyref=Help{major}{minor}:{keyref}">Français (FR) - Aide de Joomla!</site>
		<site tag="pl-PL" url="http://test1.local/www/index.php?option=com_help&amp;keyref=Help{major}{minor}:{keyref}">Polski (PL) - Pomoc do Joomla</site>
	</sites>
</joshelp>
</quote>
(test1.local/www is my proxy help system).

Switching to 'Polski' help server.

Each time I click help topic I get:

Help Site Offline
The Joomla Help Site has been taken offline. Please use the Joomla! Documentation Wiki for current version documentation.


When switch to en-GB - we can see help page contents
When switch to fr-FR - only nice _blank_ pages!


Also tested config.json for french site:
<quote>
{
	"system": {
		"error_reporting": 0
	},
	"log": {
		"level": "all"
	},
	"cache": {
		"enabled": false,
		"lifetime": 900,
		"adapter": "file"
	},
	"help": {
	    "wiki": "https://help.joomla.fr",
	    "wiki_max_redirects": 5
	}
}
</quote>

And again we get:
<quote>
Help Site Offline
The Joomla Help Site has been taken offline. Please use the Joomla! Documentation Wiki for current version documentation.
</quote>


French help was tested on multiple site (with original helpsites.xml) with no luck - blank page every time.

So is it working with other than help.jooomla.org wikis or not ? ATM - it would seem that french server worked sometime in the past but this needs to be verified with French (translation?) team.

**Comment by mbabker** [comment]
You'll need to include the `/proxy` URL segment to get things to work for historical reasons.  For reference, look at the [Router service definition](https://github.com/joomla/help.joomla.org/blob/master/src/Service/ApplicationProvider.php#L67-L82).

When I took over maintaining the `help.joomla.org` domain it was actually two Joomla installs; a legacy 1.0 site for the base domain that had a lot of the help documentation for 1.0 and 1.5, and a 1.5 install in the `/proxy` subdirectory with a custom component to pull data from a MediaWiki instance's API and render a formatted page.  The 1.5 site was upgraded to 3.x and the 1.0 site taken offline since it was never upgraded and the content severely outdated and we left behind a couple of "splash" pages for legacy purposes (in part to make sure anyone with 1.0 and 1.5 sites would still get a help screen page and for the main domain to notify that it was all taken offline).

The "upgrade" to a custom Framework app replaced all of that.  So the "splash" pages for the old content are still there and the help screen system still uses the same URL structure.

Obviously the URL structure here is best suited for the `help.joomla.org`

**Comment by mbabker** [comment]
Sorry, managed to hit enter too early...

Obviously the URL structure here is best suited for the `help.joomla.org` domain as that's what it was built primarily to work with.  So you have a couple of options, all of which depends on the amount of work you'd like to do.

The first one (obviously) is to roll with things as they are.

The second one would be to adjust the Router definition and make the default controller the `HelpScreenController` and change the controller the `/*` route map uses to the same; you can remove the other maps in that case.

The third option, if you're finding the Framework app a bit too complex to work with, would be the old CMS component at https://github.com/joomla-projects/help-proxy but I personally don't intend to give it anymore updates (which there really shouldn't be, I honestly spent more time updating the CMS with each release than working on the component code).  Just note the component doesn't support SEF URLs but beyond that it should be pretty easily configurable.

**Comment by wojsmol** [comment]
@mbabker Peoblem is solved, below is messaage to @yild in Polish language.
@yild Wersja testowa proxy działa już od piątku - po szczegóły zgłoś się do Stefana.

**Comment by yild** [comment]
SUCCESS!

Thanks @mbabker 

What I did:
as you suggested, modified router map to 
```
				$router = (new Router($container->get('Joomla\Input\Input')))
					->setContainer($container)
					->setControllerPrefix('Joomla\\Help\\Controller\\')
//					->setDefaultController('LegacyController')
					->setDefaultController('HelpScreenController')
//					->addMap('/', 'HelpScreenController')
//					->addMap('/proxy', 'HelpScreenController')
//					->addMap('/index.php', 'HelpScreenController')
//					->addMap('/proxy/index.php', 'HelpScreenController')
					->addMap('/*', 'HelpScreenController');
```

ALSO had to modify HelpScreenModel::requestPage() by commenting code that adds language code to URL:
```
/*
		// Append the language code if present and not already part of the keyref
		if ($lang !== null && strpos($title, '/') === false)
		{
			$title .= "/$lang";
		}
*/
```
there was no other way to disable creating URL like  (...){keyref}/{langcode} - even if /{langcode} was not present in help server URL, default was added ( {keyref}/en )

In addition to work with PL wiki I had to modify help server URL, and there is one thing I've noticed - each time you modify helpsites.xml file - global settings help server setting is lost and first item from list is selected (and configuration.php still have old URL value).

Thanks, Im not sure that we will launch our help site - its outdated (J3.5) and there are still problems with JHELP_ keys that Joomla team doesn't want them to be translated but our wiki is PL, so PL wiki with english URL... SEO nightmare ;) https://github.com/joomla/joomla-cms/issues/11434

Thanks for some puzzles to solve ;)


ps. for such a simple function as grabbing json from wiki, this system is way too much complex imo (especially the composer part...) ;)

**Comment by mbabker** [comment]
Honestly the whole thing should be better baked right into the CMS but that's a rant for another day.  Since the CMS serves help screens as iframes this app takes on the responsibility of rendering pages, so that complicates things a little bit.  Another big thing is the help subdomain serves over 100K sessions/month so there is a lot more code in here to make the rendered wiki API responses cacheable to make the system pretty speedy (on my local system with the cache enabled and PHP 7 running most requests responded in under 100ms) and to avoid sending a lot of traffic over to the docs wiki needlessly.  For what it's built for, it's actually a pretty smart and simple app, just not something that's easily re-purposed.
